### ISSUE TITLE
cupy import issue

### ISSUE THREAD

**Issue by Sh4zKh4n** [mritools/cupyimg#16]
So I thought I would try to use cupyimg because of the really interesting work but when I go to import I get the following error, it seems to think it should be pulling something from cupy when it should be pulling from a cupyimg file i.e. cupyimg utils and not cupy.util (which is my guess)

```python
import numpy as np
import cupy
import scipy.ndimage as ndi
from cupyimg.scipy.ndimage import uniform_filter

```
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-beb6e82ba862> in <module>
      2 import cupy
      3 import scipy.ndimage as ndi
----> 4 from cupyimg.scipy.ndimage import uniform_filter

~/miniconda3/envs/img_linux2/lib/python3.8/site-packages/cupyimg/__init__.py in <module>
     28     memoize = cupy.memoize
     29 
---> 30 from ._misc import convolve_separable  # noqa
     31 from .version import __version__  # noqa
     32 

~/miniconda3/envs/img_linux2/lib/python3.8/site-packages/cupyimg/_misc.py in <module>
      8 import numpy
      9 
---> 10 from cupyimg.scipy.ndimage import convolve1d
     11 
     12 __all__ = ["convolve_separable"]

~/miniconda3/envs/img_linux2/lib/python3.8/site-packages/cupyimg/scipy/ndimage/__init__.py in <module>
----> 1 from .filters import *  # noqa
      2 from .measurements import *  # noqa
      3 from .morphology import *  # noqa
      4 
      5 from cupyimg.scipy.ndimage.fourier import fourier_ellipsoid  # NOQA

~/miniconda3/envs/img_linux2/lib/python3.8/site-packages/cupyimg/scipy/ndimage/filters.py in <module>
    496 
    497 
--> 498 @cupy._util.memoize(for_each_device=True)
    499 def _get_correlate_kernel(mode, w_shape, int_type, offsets, cval):
    500     return _filters_core._generate_nd_kernel(

AttributeError: module 'cupy' has no attribute '_util'
```

**Comment by grlee77** [comment]
For now, if the functions you need are the ones from `cupyimg.scipy.ndimage` or `cupyimg.numpy`, I would recommend using the master branch of [CuPy](https://github.com/cupy/cupy)  where functions from `cupyimg.scipy.ndimage.*` are available in cupy via `cupyx.scipy.ndimage.*`. The versions there are regularly tested on various GPU hardware and CUDA versions and should be more reliable long-term.

That said, I will also work on fixing the repository here as well.

**Comment by Sh4zKh4n** [comment]
Thanks@grlee77 , I alway find it a pain to install the latest version of cupy. I've never got all the dependencies right when installing. I can try again though. Thanks for acknowledging.

**Comment by grlee77** [comment]
Okay, I pushed some small fixes to master so it should be working with CuPy 8.3 again. For 9.x, there are still likely to be some failures in kernel compilation due to some upstream changes.

**Comment by Sh4zKh4n** [comment]
thanks @grlee77
